export type M3uQuality = 'HD' | 'FHD' | 'UHD' | 'SD';
export type M3uEntry = { name: string; url: string; group?: string; tvgId?: string; tvgName?: string; tvgLogo?: string; quality: M3uQuality; country: string; language: string; timeshift?: string; variant: 'original' | 'timeshift' };
export type M3uPreview = { total: number; accepted: number; invalid: number; duplicates: number; blocked: number; entries: M3uEntry[] };
const blockedTerms = ['adult', '18+', 'xxx', 'erotica', 'эротика', 'взрослые', 'porn'];
function publicHttps(value: string) { try { const url = new URL(value); const host = url.hostname.toLowerCase(); return url.protocol === 'https:' && host !== 'localhost' && !host.endsWith('.localhost') && !/^(10|127|169\.254)\./.test(host) && !/^192\.168\./.test(host) && !/^172\.(1[6-9]|2\d|3[0-1])\./.test(host); } catch { return false; } }
function attr(info: string, key: string) { return info.match(new RegExp(`${key}="([^"]*)"`, 'i'))?.[1]; }
function quality(name: string): M3uQuality { if (/\bUHD|4K\b/i.test(name)) return 'UHD'; if (/\bFHD\b/i.test(name)) return 'FHD'; if (/\bHD\b/i.test(name)) return 'HD'; return 'SD'; }
function country(group: string) { return /узбекистан|o['’ʻ]?zbek|uzbekistan|\buz\b/i.test(group) ? 'UZ' : 'INT'; }
function cleanName(name: string) { return name.replace(/\s+(HD|FHD|UHD|4K|orig)\b/gi, '').replace(/\s+\+\d+(\s|$).*$/i, '').trim(); }
export function previewM3u(input: string, maxEntries = 5000): M3uPreview { const lines = input.split(/\r?\n/).map((line) => line.trim()); const entries: M3uEntry[] = []; let invalid = 0; let blocked = 0; let duplicates = 0; const fingerprints = new Set<string>(); for (let i = 0; i < lines.length && entries.length < maxEntries; i += 1) { const info = lines[i]; if (!info.startsWith('#EXTINF:')) continue; const rawName = info.split(',').slice(1).join(',').trim(); const url = lines[i + 1] ?? ''; const group = attr(info, 'group-title') ?? ''; if (!rawName || !publicHttps(url)) { invalid += 1; i += 1; continue; } if (blockedTerms.some((term) => `${group} ${rawName}`.toLowerCase().includes(term))) { blocked += 1; i += 1; continue; } const id = attr(info, 'tvg-id'); const key = `${id ?? cleanName(rawName).toLowerCase()}|${country(group)}|${quality(rawName)}`; if (fingerprints.has(key)) { duplicates += 1; i += 1; continue; } fingerprints.add(key); const shift = rawName.match(/\+(\d+)/)?.[1]; entries.push({ name: cleanName(rawName), url, group, tvgId: id, tvgName: attr(info, 'tvg-name'), tvgLogo: attr(info, 'tvg-logo'), quality: quality(rawName), country: country(group), language: country(group) === 'UZ' ? 'uz' : 'ru', timeshift: shift, variant: shift ? 'timeshift' : 'original' }); i += 1; } return { total: entries.length + invalid + blocked + duplicates, accepted: entries.length, invalid, blocked, duplicates, entries }; }
export function parseSafeM3u(input: string, maxEntries = 5000): M3uEntry[] { return previewM3u(input, maxEntries).entries; }
