export type M3uQuality = 'HD' | 'FHD' | 'UHD' | 'SD';
export type M3uEntry = { name: string; url: string; group?: string; tvgId?: string; tvgLogo?: string; quality: M3uQuality; country: string; timeshift?: string; rejected?: boolean; rejectionReason?: string };
export type M3uPreview = { total: number; valid: number; invalid: number; duplicates: number; rejected: number; entries: M3uEntry[] };
function isPublicHttpsUrl(value: string): boolean { try { const url = new URL(value); if (url.protocol !== 'https:') return false; const host = url.hostname.toLowerCase(); return host !== 'localhost' && !host.endsWith('.localhost') && !/^(10|127)\./.test(host) && !/^192\.168\./.test(host) && !/^169\.254\./.test(host) && !/^172\.(1[6-9]|2\d|3[0-1])\./.test(host); } catch { return false; } }
function qualityOf(name: string): M3uQuality { const upper = name.toUpperCase(); return upper.includes('UHD') || upper.includes('4K') ? 'UHD' : upper.includes('FHD') ? 'FHD' : upper.includes('HD') ? 'HD' : 'SD'; }
function countryOf(group: string, name: string): string { return /узбекистан|o['’ʻ]?zbek|uzbekistan|(^|\s)uz(\s|$)/i.test(`${group} ${name}`) ? 'UZ' : 'INT'; }
function timeshiftOf(name: string): string | undefined { return name.match(/\+(\d+)/)?.[1] ?? (name.toLowerCase().includes('orig') ? 'orig' : undefined); }
export function parseM3uPreview(input: string, maxEntries = 5000): M3uPreview { const lines = input.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const entries: M3uEntry[] = []; let invalid = 0; let rejected = 0; const seen = new Set<string>(); for (let index = 0; index < lines.length && entries.length < maxEntries; index += 1) { const info = lines[index]; if (!info.startsWith('#EXTINF:')) continue; const url = lines[index + 1] ?? ''; const name = info.split(',').slice(1).join(',').trim(); const attribute = (key: string) => info.match(new RegExp(`${key}="([^"]*)"`, 'i'))?.[1] ?? ''; const group = attribute('group-title'); const blocked = /adult|18\+|xxx|porn|эротика|взрослые/i.test(`${group} ${name}`); if (!name || !isPublicHttpsUrl(url)) { invalid += 1; index += 1; continue; } if (blocked) { rejected += 1; index += 1; continue; } const fingerprint = `${attribute('tvg-id').toLowerCase()}|${name.toLowerCase()}|${url.split('?')[0]}`; if (seen.has(fingerprint)) { entries.push({ name, url, group, tvgId: attribute('tvg-id'), tvgLogo: attribute('tvg-logo'), quality: qualityOf(name), country: countryOf(group, name), timeshift: timeshiftOf(name) }); index += 1; continue; } seen.add(fingerprint); entries.push({ name, url, group, tvgId: attribute('tvg-id'), tvgLogo: attribute('tvg-logo'), quality: qualityOf(name), country: countryOf(group, name), timeshift: timeshiftOf(name) }); index += 1; } return { total: entries.length + invalid + rejected, valid: entries.length, invalid, duplicates: Math.max(0, entries.length - seen.size), rejected, entries }; }
export function parseSafeM3u(input: string, maxEntries = 5000): M3uEntry[] { return parseM3uPreview(input, maxEntries).entries; }
