'use client';
import Link from 'next/link';
import { motion } from 'motion/react';
import { ArrowUpRight, Radio, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { Channel } from '@/lib/demo';

function normalize(value: string) { return value.toLocaleLowerCase().replace(/[ʻʼ‘’`']/g, "'").replace(/o'/g, 'o').replace(/g'/g, 'g').normalize('NFD').replace(/[\u0300-\u036f]/g, ''); }
export function ChannelCatalog({ channels }: { channels: Channel[] }) {
  const [category, setCategory] = useState('All'); const [country, setCountry] = useState('All'); const [quality, setQuality] = useState('All'); const [query, setQuery] = useState('');
  const categories = ['All', ...Array.from(new Set(channels.map((channel) => channel.category)))];
  const filtered = useMemo(() => channels.filter((channel) => (category === 'All' || channel.category === category) && (country === 'All' || channel.country === country) && (quality === 'All' || channel.quality === quality) && (!query || normalize(`${channel.name} ${channel.program} ${channel.category} ${channel.language}`).includes(normalize(query)))), [channels, category, country, quality, query]);
  return <div className="catalog-layout"><aside className="filter-rail"><div className="filter-title"><span>Filter signal</span><SlidersHorizontal size={16} /></div><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a channel" /></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Country<select value={country} onChange={(event) => setCountry(event.target.value)}><option>All</option><option>UZ</option><option>INT</option></select></label><label>Quality<select value={quality} onChange={(event) => setQuality(event.target.value)}><option>All</option><option>HD</option><option>FHD</option><option>4K</option></select></label></aside><section className="catalog-results"><div className="catalog-result-head"><div><p className="eyebrow">Live directory</p><h1>Every signal, <em>in order.</em></h1></div><span className="mono">{filtered.length} channels</span></div>{filtered.length === 0 ? <div className="catalog-empty"><Radio size={24} /><h2>No signal found</h2><p>Try clearing a filter or searching another phrase.</p></div> : <div className="catalog-grid">{filtered.map((channel, index) => <motion.div key={channel.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.03 }}><Link href={`/live/${channel.id}`} className={`directory-card tone-${channel.tone}`}><div className="directory-art"><span>{channel.shortName}</span><b className={channel.live ? 'is-live' : ''}>{channel.live ? 'LIVE' : 'OFF AIR'}</b><ArrowUpRight size={18} /></div><div className="directory-copy"><div><h3>{channel.name}</h3><p>{channel.program}</p></div><span className="quality-tag">{channel.quality}</span></div></Link></motion.div>)}</div>}</section></div>;
}
